<?php

declare(strict_types=1);

namespace Unquam\NetteMaker\Composer;

use Composer\Composer;
use Composer\EventDispatcher\EventSubscriberInterface;
use Composer\IO\IOInterface;
use Composer\Plugin\PluginInterface;
use Composer\Script\ScriptEvents;
use Composer\Script\Event as ScriptEvent;

class Plugin implements PluginInterface, EventSubscriberInterface
{
    /** @var Composer */
    private $composer;

    public function activate(Composer $composer, IOInterface $io): void
    {
        $this->composer = $composer;
    }

    public function deactivate(Composer $composer, IOInterface $io): void
    {
    }

    public function uninstall(Composer $composer, IOInterface $io): void
    {
        $projectRoot = dirname($composer->getConfig()->get('vendor-dir'));
        $runner = $projectRoot . '/nette';

        if (file_exists($runner)) {
            @unlink($runner);
        }
    }

    public static function getSubscribedEvents(): array
    {
        return [
            ScriptEvents::POST_AUTOLOAD_DUMP => 'onPostAutoloadDump',
        ];
    }

    /**
     * Gets Composer instance from the event for guaranteed availability.
     */
    public function onPostAutoloadDump(ScriptEvent $event): void
    {
        $composer = $event->getComposer();
        $projectRoot = dirname($composer->getConfig()->get('vendor-dir'));

        $this->createRunnerFile($projectRoot);
        $this->createConfigFile($projectRoot);
    }

    private function createRunnerFile(string $projectRoot): void
    {
        $runnerFile = $projectRoot . '/nette';

        if (file_exists($runnerFile)) {
            return;
        }

        $content = "#!/usr/bin/env php\n" .
            "<?php\n\n" .
            "// Automatically generated by unquam/nette-maker\n" .
            "declare(strict_types=1);\n\n" .
            "\$autoload = __DIR__ . '/vendor/autoload.php';\n\n" .
            "if (!file_exists(\$autoload)) {\n" .
            "    fwrite(STDERR, \"vendor/autoload.php not found. Run 'composer install' first.\\n\");\n" .
            "    exit(1);\n" .
            "}\n\n" .
            "require \$autoload;\n\n" .
            "use Unquam\\NetteMaker\\Application;\n\n" .
            "\$app = new Application(__DIR__ . '/nette-maker.neon');\n" .
            "exit(\$app->run());\n";

        if (file_put_contents($runnerFile, $content) !== false) {
            @chmod($runnerFile, 0755);
        }
    }

    private function createConfigFile(string $projectRoot): void
    {
        $configFile = $projectRoot . '/nette-maker.neon';

        if (file_exists($configFile)) {
            return;
        }

        $stub = dirname(__DIR__, 2) . '/stubs/nette-maker.neon.stub';

        if (file_exists($stub)) {
            copy($stub, $configFile);
            return;
        }

        // Updated default fallback string layout with "directories" array block support
        $default = "database:\n" .
            "    dsn: 'mysql:host=127.0.0.1;dbname=your_database'\n" .
            "    user: root\n" .
            "    password: ''\n\n" .
            "migrations:\n" .
            "    directory: db/migrations\n\n" .
            "seeders:\n" .
            "    directory: db/seeders\n\n" .
            "factories:\n" .
            "    directory: db/factories\n\n" .
            "cache:\n" .
            "    directories:\n" .
            "        - temp\n";

        file_put_contents($configFile, $default);
    }
}