<?php

declare(strict_types=1);

namespace Unquam\NetteMaker\Composer;

use Composer\Script\Event;

class ScriptHandler
{
    public static function install(Event $event): void
    {
        $projectRoot = dirname($event->getComposer()->getConfig()->get('vendor-dir'));

        self::createRunnerFile($projectRoot, $event);
        self::createConfigFile($projectRoot, $event);
    }

    private static function createRunnerFile(string $projectRoot, Event $event): void
    {
        $runnerFile = $projectRoot . '/nette';

        if (file_exists($runnerFile)) {
            return;
        }

        // A minimal shell wrapper that delegates to the Composer binary.
        $content = "#!/usr/bin/env php\n" .
            "<?php\n\n" .
            "// Automatically generated by unquam/nette-maker\n" .
            "// Run: php nette <command> [options]\n\n" .
            "declare(strict_types=1);\n\n" .
            "\$autoload = __DIR__ . '/vendor/autoload.php';\n\n" .
            "if (!file_exists(\$autoload)) {\n" .
            "    fwrite(STDERR, \"vendor/autoload.php not found. Run 'composer install' first.\n\");\n" .
            "    exit(1);\n" .
            "}\n\n" .
            "require \$autoload;\n\n" .
            "use Unquam\\NetteMaker\\Application;\n\n" .
            "\$app = new Application(__DIR__ . '/nette-maker.neon');\n" .
            "exit(\$app->run());\n";

        if (file_put_contents($runnerFile, $content) !== false) {
            @chmod($runnerFile, 0755);
            $event->getIO()->write('<info>Nette Maker: created `nette` runner in project root.</info>');
        } else {
            $event->getIO()->writeError('<warning>Nette Maker: failed to create `nette` runner.</warning>');
        }
    }

    private static function createConfigFile(string $projectRoot, Event $event): void
    {
        $configFile = $projectRoot . '/nette-maker.neon';

        if (file_exists($configFile)) {
            return;
        }

        $stub = dirname(__DIR__, 2) . '/stubs/nette-maker.neon.stub';

        if (file_exists($stub)) {
            copy($stub, $configFile);
        } else {
            $default = "database:\n" .
                "    dsn: 'mysql:host=127.0.0.1;dbname=your_database'\n" .
                "    user: root\n" .
                "    password: ''\n\n" .
                "migrations:\n" .
                "    directory: db/migrations\n";

            file_put_contents($configFile, $default);
        }

        $event->getIO()->write('<info>Nette Maker: created `nette-maker.neon` in project root.</info>');
    }
}